exports.up = knex =>
knex.schema.createTable('users', table => {
  table.increments('id').primary()
  table.string('email').unique()
  table.string('password')
  table.string('password_reset_token')
  table.timestamp('reset_token_expiry')
  table.bool('is_verified').defaultTo(false)
  table.bool('is_agency')
  table.bool('onboarded').defaultTo(false)
  table.enum('role', ['brand', 'influencer', 'both'])
  table.string('vat_number').unique()
  table.string('company_name')
  table.string('company_address')
  table.string('company_address2')
  table.string('company_city')
  table.string('company_country')
  table.string('company_state')
  table.string('company_zip_code')
  table.string('billing_name')
  table.string('billing_address')
  table.string('billing_address2')
  table.string('billing_city')
  table.string('billing_country')
  table.string('billing_state')
  table.string('billing_zip_code')
  table.string('contact_name').unique()
  table.string('contact_email').unique()
  table.string('contact_number').unique()
  table.timestamp('last_seen').defaultTo(knex.fn.now())
  table.timestamps(true, true)
})

exports.down = knex => knex.schema.dropTableIfExists('users')
